### PR TITLE
Add dagger 2 diagrams.

### PR DESCRIPTION
**Pull request by ppiech**
I'd like to add more content to the dagger 2 write up, including these diagrams for reference.

### CODE REVIEW

**Comment by nesquena** [comment]
@rogerhu

**Comment by ppiech** [comment]
Not sure if i'm breaking any etiquette in this project, but I started updating the wiki doc for dagger as well.

**Comment by nesquena** [comment]
No etiquette broken, please feel free to improve any of the guides as you see fit :)

**Comment by nesquena** [comment]
I've merged your diagrams as well, feel free to include them in the guide to help illustrate how it works. We definitely need help reviewing our Dagger 2 guide.

**Comment by rogerhu** [comment]
Feel free to review and edit...although do you think the diagrams actually
make things clearer?  It seems at the very least they need explanation.
On Dec 15, 2015 12:02 PM, "Nathan Esquenazi" <notifications@github.com>
wrote:

I've merged your diagrams as well, feel free to include them in the guide
to help illustrate how it works. We definitely need help reviewing our
Dagger 2 guide.

—
Reply to this email directly or view it on GitHub
<https://github.com/codepath/android_guides/pull/124#issuecomment-164878499>
.

**Comment by ppiech** [comment]
Many thanks for the quick merge!

**Pull request merged**
